-- Run this in your Supabase SQL editor to create the `stories` table and seed entries.

-- 1. Create stories table if it doesn't exist
create table if not exists stories (
  id bigint generated by default as identity primary key,
  mythology text not null,
  title text not null,
  summary text,
  content text,
  source_url text,
  image_url text,
  created_at timestamptz default now()
);

-- 2. Clear existing data to prevent duplicates (and reset ID counter)
truncate table stories restart identity;

-- 3. Insert sample stories (one per mythology as examples)
insert into stories (mythology, title, summary, content, source_url, image_url) values
('Yunani','Perjuangan Herakles','Ringkasan dua-tiga kalimat tentang dua belas tugas sang pahlawan.','Konten lebih panjang tentang dua belas tugas Herakles dan signifikansinya dalam mitologi Yunani.','','https://picsum.photos/seed/herakles/800/500'),
('Mesir','Kebangkitan Osiris','Ringkasan singkat tentang pembunuhan Osiris oleh Set dan kebangkitannya.','Kisah detail Osiris, peran Isis, dan dampaknya terhadap tradisi Mesir kuno.','','https://picsum.photos/seed/osiris_story/800/500'),
('Nordik','Ragnarök','Ringkasan singkat akhir zaman versi Nordik.','Deskripsi pertempuran terakhir para dewa, nasib Odin dan Thor, serta kelahiran kembali dunia.','','https://picsum.photos/seed/ragnarok/800/500'),
('Mesopotamia','Epos Gilgamesh','Ringkasan singkat perjalanan Gilgamesh mencari keabadian.','Rincian tentang Enkidu, banjir besar, dan penemuan makna hidup.','','https://picsum.photos/seed/gilgamesh_story/800/500'),
('Celtic','Morrígan dan Pertempuran','Ringkasan singkat keterlibatan Morrígan dalam peperangan.','Kisah-kisah pengaruh Morrígan terhadap nasib dan kemenangan.','','https://picsum.photos/seed/morrigan_story/800/500'),
('Jepang','Penyembunyian Amaterasu','Ringkasan singkat Amaterasu bersembunyi di gua.','Cerita lengkap tentang para kami yang memancing Amaterasu keluar demi mengembalikan cahaya.','','https://picsum.photos/seed/amaterasu_story/800/500'),
('China','Perjalanan Chang’e ke Bulan','Ringkasan singkat naiknya Chang’e ke bulan.','Detail legenda, Hou Yi, dan festival terkait di budaya Tionghoa.','','https://picsum.photos/seed/change_story/800/500'),
('Aztec','Penciptaan Matahari dan Bulan','Ringkasan singkat tentang kelahiran matahari dan bulan.','Cerita pengorbanan para dewa dan penetapan tata kosmik dalam mitologi Aztec.','','https://picsum.photos/seed/aztec_story/800/500');
